name: Deploy to AWS Elastic Beanstalk

on:
  push:
    tags:
      - "v*" # or your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get the version
        id: get_version
        run: |
          VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install

      - name: Build Angular app
        run: pnpm build

      - name: Generate deployment package
        run: |
          cd dist/ecom
          zip -r ../../deploy.zip . ../../Procfile
          cd ../..

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ecom
          environment_name: stagging
          version_label: ${{ steps.get_version.outputs.version }}
          region: ap-south-1 # or your preferred AWS region
          deployment_package: deploy.zip
          use_existing_version_if_available: true
          wait_for_deployment: true
          wait_for_environment_recovery: 30
